export const PROVIDER_HTTP_CLIENT = Symbol("PROVIDER_HTTP_CLIENT");
export const PROVIDER_CONFIGURATION_REGISTRY = Symbol("PROVIDER_CONFIGURATION_REGISTRY");
export const COURIER_PROVIDER_COLLECTION = Symbol("COURIER_PROVIDER_COLLECTION");
export const PROVIDER_HEALTH_REPORTER = Symbol("PROVIDER_HEALTH_REPORTER");
