import {
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  CreditCard,
  Flag,
  Gauge,
  History,
  KeyRound,
  LifeBuoy,
  Megaphone,
  ReceiptText,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  TicketPercent,
  Truck,
  UserCog,
  Users
} from "lucide-react";

export const portalNav = [
  { href: "/dashboard", label: "Dashboard", icon: Gauge },
  { href: "/search", label: "Fraud Search", icon: Search },
  { href: "/search/history", label: "Search History", icon: History },
  { href: "/billing", label: "Billing", icon: CreditCard },
  { href: "/billing/plans", label: "Plans", icon: ReceiptText },
  { href: "/billing/invoices", label: "Invoices", icon: BookOpen },
  { href: "/billing/subscription", label: "Subscription", icon: ShieldCheck },
  { href: "/billing/usage", label: "Usage", icon: Activity },
  { href: "/api-keys", label: "API Keys", icon: KeyRound },
  { href: "/merchant-accounts", label: "Merchant Accounts", icon: BriefcaseBusiness },
  { href: "/courier-orders", label: "Courier Orders", icon: Truck },
  { href: "/courier-reports", label: "Courier Reports", icon: BarChart3 },
  { href: "/profile", label: "Profile", icon: UserCog },
  { href: "/security", label: "Security", icon: Shield },
  { href: "/sessions", label: "Sessions", icon: Activity },
  { href: "/notifications", label: "Notifications", icon: Bell },
  { href: "/saved-searches", label: "Saved Searches", icon: Flag },
  { href: "/favorites", label: "Favorites", icon: TicketPercent }
] as const;

export const adminNav = [
  { href: "/admin", label: "Admin Overview", icon: Gauge },
  { href: "/admin/users", label: "Users", icon: Users },
  { href: "/admin/roles", label: "Roles", icon: ShieldCheck },
  { href: "/admin/permissions", label: "Permissions", icon: Shield },
  { href: "/admin/merchant-credentials", label: "Merchant Credentials", icon: BriefcaseBusiness },
  { href: "/admin/courier-providers", label: "Courier Providers", icon: Activity },
  { href: "/admin/api-keys", label: "API Keys", icon: KeyRound },
  { href: "/admin/plans", label: "Plans", icon: ReceiptText },
  { href: "/admin/subscriptions", label: "Subscriptions", icon: CreditCard },
  { href: "/admin/coupons", label: "Coupons", icon: TicketPercent },
  { href: "/admin/promo-campaigns", label: "Promo Campaigns", icon: Megaphone },
  { href: "/admin/invoices", label: "Invoices", icon: BookOpen },
  { href: "/admin/payments", label: "Payments", icon: CreditCard },
  { href: "/admin/analytics", label: "Analytics", icon: Gauge },
  { href: "/admin/search-logs", label: "Search Logs", icon: Search },
  { href: "/admin/audit-logs", label: "Audit Logs", icon: History },
  { href: "/admin/announcements", label: "Announcements", icon: Megaphone },
  { href: "/admin/feature-flags", label: "Feature Flags", icon: Flag },
  { href: "/admin/system-settings", label: "System Settings", icon: Settings },
  { href: "/admin/maintenance", label: "Maintenance", icon: SlidersHorizontal },
  { href: "/admin/redis", label: "Redis", icon: Activity },
  { href: "/admin/queues", label: "Queues", icon: Activity },
  { href: "/admin/monitoring", label: "Monitoring", icon: LifeBuoy },
  { href: "/admin/health", label: "Health", icon: Activity }
] as const;
